version: "3.8"

services:

  db:
    container_name: postgres_database
    image: postgres:14.7-alpine
    env_file:
      - .env

  backend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    container_name: django_backend
    depends_on:
      - db
    restart: always
    env_file:
      - .env


volumes:
  postgres_data:
