version: "3.8"

services:

  db:
    container_name: postgres_database
    image: postgres:14.7-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - ./.env
    restart: always
    networks:
      - django_network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - django_network

  backend:
    container_name: django_backend
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    entrypoint: ./infra/backend_entrypoint
    volumes:
      - ../src/static:/app/src/static
      - ../src/media:/app/src/media
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    networks:
      - django_network

  celery:
    container_name: celery_worker
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    entrypoint: ./infra/celery_worker_entrypoint
    volumes:
      - ../src/static:/app/src/static
      - ../src/media:/app/src/media
    depends_on:
      - db
      - redis
      - backend
    restart: always
    env_file:
      - ./.env
    networks:
      - django_network

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:${NGINX_PORT}"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ../src/static:/var/html/static/
      - ../src/media:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - backend
    restart: always
    networks:
      - django_network

volumes:
  postgres_db:
  static:
  media:


networks:
  django_network:
