# Generated by Django 4.2.5 on 2023-09-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата продажи")),
                (
                    "sales_type",
                    models.BooleanField(verbose_name="Наличие промо"),
                ),
                (
                    "sales_units",
                    models.IntegerField(
                        verbose_name="Число проданных товаров без промо"
                    ),
                ),
                (
                    "sales_units_promo",
                    models.IntegerField(
                        verbose_name="Число проданных товаров c промо"
                    ),
                ),
                (
                    "sales_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма продаж без промо в рублях",
                    ),
                ),
                (
                    "sales_rub_promo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма продаж c промо в рублях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(max_length=255, verbose_name="Группа"),
                ),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="Категория"),
                ),
                (
                    "subcategory",
                    models.CharField(
                        max_length=256, verbose_name="Подкатегория"
                    ),
                ),
                ("sku", models.CharField(max_length=256, verbose_name="СКЮ")),
                ("uom", models.IntegerField(verbose_name="Единицы измерения")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.CharField(max_length=255, verbose_name="Магазин"),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=255, verbose_name="Населенный пункт"
                    ),
                ),
                (
                    "division",
                    models.CharField(max_length=256, verbose_name="Дивизион"),
                ),
                (
                    "type_format",
                    models.IntegerField(verbose_name="Формат магазина"),
                ),
                (
                    "loc",
                    models.IntegerField(
                        verbose_name="Локация/окружение магазина"
                    ),
                ),
                ("size", models.IntegerField(verbose_name="Размер магазина")),
                ("is_active", models.BooleanField(verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=[
                            "store",
                            "city",
                            "division",
                            "type_format",
                            "loc",
                            "size",
                        ],
                        name="forecasts_s_store_549749_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=(
                    "store",
                    "city",
                    "division",
                    "type_format",
                    "loc",
                    "size",
                ),
                name="unique_stores",
            ),
        ),
        migrations.AddIndex(
            model_name="sku",
            index=models.Index(
                fields=["group", "category", "subcategory", "sku", "uom"],
                name="forecasts_s_group_9b9b90_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sku",
            constraint=models.UniqueConstraint(
                fields=("group", "category", "subcategory", "sku", "uom"),
                name="unique_product",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sku_sales",
                to="forecasts.sku",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="store_sales",
                to="forecasts.store",
                verbose_name="Магазин",
            ),
        ),
    ]
