name: Push to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_BACKEND_USERNAME }}
          password: ${{ secrets.DOCKER_BACKEND_PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_BACKEND_USERNAME }}/lenta_backend:latest

      - name: Push celery to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra/celery/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_BACKEND_USERNAME }}/lenta_celery:latest
